FORMAT: 1A
HOST: http://www.google.com

# intime
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

## GET /api/v2/timeline 

+ Response 200 (application/json;charset=utf-8)

## POST /api/v2/submit 

+ Response 200 (application/json;charset=utf-8)

## POST /api/v2/seen 

+ Response 200 (application/json;charset=utf-8)

## POST /api/v2/registerAPNS 

+ Response 200 (application/json;charset=utf-8)

## POST /api/v2/syncDeleted 

+ Response 200 (application/json;charset=utf-8)

## POST /api/v2/verifyReceipt 

+ Response 200 (application/json;charset=utf-8)

## GET / 

+ Response 200 (application/json;charset=utf-8)

        {
          "message": "Welcome to the API"
        }
        
## GET /a/b/c 

+ Response 404 (application/json;charset=utf-8)

        {
          "message": "Not found"
        }
        
## GET /api/v2/status?api_key=b0eba98179 

+ Response 200 (application/json;charset=utf-8)

## GET /api/v2/statusAuth 

+ Response 404 (application/json;charset=utf-8)

        {
          "message": "Not found"
        }
        
## POST /api/v2/authorize 

+ Response 400 (application/json;charset=utf-8)

        {
          "message": "Incorrect email"
        }
        
## POST /api/v2/desauthorize 

+ Response 404 (application/json;charset=utf-8)

        {
          "message": "Not found"
        }
        
## GET /user/53308b1159b0374996000001 

+ Response 404 (application/json;charset=utf-8)

        {
          "message": "Not found"
        }
        
## GET /api/v2/intime/count 

+ Response 200 (application/json;charset=utf-8)

## GET /api/v2/intime 

+ Response 200 (application/json;charset=utf-8)

## DELETE /api/v2/intime 

+ Response 200 (application/json;charset=utf-8)

## POST /api/v2/friends/check 

+ Response 200 (application/json;charset=utf-8)

## GET /api/v2/friends 

+ Response 200 (application/json;charset=utf-8)

## POST /api/v2/friend/block 

+ Response 200 (application/json;charset=utf-8)

## GET /api/v2/profile 

+ Response 200 (application/json;charset=utf-8)

## POST /api/v2/profile 

+ Response 200 (application/json;charset=utf-8)

## POST /api/v2/tag 

+ Response 200 (application/json;charset=utf-8)

## POST /api/v2/tag 

+ Response 200 (application/json;charset=utf-8)

## POST /api/v2/like 

+ Response 200 (application/json;charset=utf-8)

## POST /api/v2/unlike 

+ Response 200 (application/json;charset=utf-8)

## POST /api/v2/comment 

+ Response 200 (application/json;charset=utf-8)

## DELETE /api/v2/comment 

+ Response 200 (application/json;charset=utf-8)


